export const ACTION_TYPES = {
  GET_AUTH_TOKEN: 'getAuthToken',
  RENEW_TOKEN: 'renewToken',
  CREATE_MEETING_MINUTE: 'createMeetingMinute',
  CHANGE_LANG_PREFERENCE: 'changeLangPreference',
  OPEN_CONVERSATION_HISTORY: 'openConversationHistory',
  SET_LANGUAGE: 'setLanguage',
  MIC_MUTE: 'micMute',
  USER_AUTHORIZED: 'userAuthorized',
  MEETING_LEFT: 'meetingLeft',
  CLOSE_HISTORY_WINDOW: 'closeHistoryWindow',
  GOOGLE_ANALYTICS: 'googleAnalytics',
  ACCESS_MEETING_MINUTE: 'accessMeetingMinute',
  UPDATE_CHECK: 'updateCheck',
  NEW_VERSION: 'newVersion',
};

export const EVENTS = {
  VOICE_RECOGNITION_STARTED: 'voice_recognition_started',
  VOICE_RECOGNITION_STOPPED: 'voice_recognition_stopped',
  SESSION_STARTED: 'session_started',
  SESSION_STOPPED: 'session_stopped',
  SPEECH_STARTED: 'speech_started',
  SPEECH_ENDED: 'speech_ended',
  RECOGNIZING: 'recognizing',
  RECOGNIZED: 'recognized',
  CANCELED: 'canceled',
  UNAUTHORIZED_USER: 'unauthorized_user',
  SPEECH_RECOGNITION_NOT_AVAILABLE: 'speech_recognition_not_available',
  MIC_ON_MUTE: 'mic_on_mute',
  CONVERSATION_WINDOW: 'Conversation Window',
  LANGUAGE_CHANGED: 'Language Changed',
  SPEECH_TRANSCRIPTION: 'Speech Transcription',
  SPEECH_TRANSLATION: 'Speech Translation',
  MOM_STARTED: 'meeting_minute_started',
  COPY_MOM_LINK: 'copy_meeting_minute_link',
  FONT_SIZE_UPDATED: 'font_size',
};
